### ISSUE TITLE
Instagram button?

### ISSUE THREAD

**Issue by GrillinFool** [jasonbutler42/grillinfools#53]
Along with a FB, Pinterest, Google +, and Twitter buttons, we need to add Instagram (GrillinFools). The micro SD card in my phone that has gone from phone to phone to phone is full of great pics for Instagram So much so, that I had 700 followers on New Years Eve and have close to 1600 right now because I keep tossing out archive pics.

**Comment by jasonbutler42** [comment]
A few things:
1. The FB, Google+, Pinterest, and Twitter buttons are all part of a specific plugin that helps share the current post. Adding Instagram to that list might not make sense in that context since you can't really "share" anything that way on Instagram. Also, Instagram isn't built into the plugin, so it would either be really hinky to add it or I'd have to break the plugin as a dependency and I really don't want to do that.
2. There's a "follow us" link at the bottom of the Instagram feed. We could make it more prominent by making it bigger or moving it up above the pictures or putting it both above and below, etc.

**Comment by GrillinFool** [comment]
Yeah, that makes more sense. Not really share but a follow. Since we have the Instagram on the right, we need people to be able to easily follow that feed.

**Comment by jasonbutler42** [comment]
I think we have Instagram covered pretty well.
